version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/database_name
      SECRET_KEY: your-secret-key # Change this to a strong, random key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - db
    # If you want to enable live reloading for development, uncomment the following:
    # volumes:
    #   - ./backend:/app
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db-data: